# Generated by Django 6.0.6 on 2026-09-13 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='quantidade_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidade', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('L', 'L'), ('ml', 'ml'), ('unidade', 'unidade')], default='unidade', max_length=20)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='core.receita')),
            ],
        ),
    ]
