# Generated by Django 5.2.7 on 2026-10-04 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenPreparation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Em preparo', 'Em preparo'), ('Concluído', 'Concluído')], default='Em preparo', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_preparations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
