services:
  web:
    build:
      context: .
    env_file:
      - .env
    environment:
      DJANGO_DB_PATH: /app/data/db.sqlite3
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
    entrypoint: ["/app/docker/entrypoint.sh"]
    command: ["gunicorn", "setup.wsgi:application", "--bind", "0.0.0.0:8000"]

volumes:
  sqlite_data:
